# Tema 1 - Matrices

Vamos a ver cómo crear una matriz uitlizando la librería `numpy`.

In [1]:
row = [1,2,3]
row

[1, 2, 3]

In [2]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [3]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
M[1][1]

5.0

In [29]:
M[0][0]

1.0

In [30]:
M[0] # Para ver la primera fila

array([1., 2., 3.])

In [31]:
for row in M:
    print(row[0])

1.0
4.0
7.0


In [ ]:
2*M

In [ ]:
import numpy as np

In [9]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.shape(M)

(3, 3)

In [13]:
A = np.array([[1,2],[3,4]])
print(A)
B = np.array([[3,0],[1,-1]])
print(B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]


In [14]:
print(A + B) # Para sumar matrices

[[4 2]
 [4 3]]


In [15]:
print(A.dot(B)) # Producto matricial

[[ 5 -2]
 [13 -4]]


In [16]:
print(A.transpose())

[[1 3]
 [2 4]]


In [17]:
np.linalg.matrix_rank(A)

2

In [18]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

In [19]:
np.linalg.det(A)

-2.0000000000000004

In [20]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [21]:
np.linalg.inv(A).dot(A) # No lo parece pero es la matriz identidad

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [22]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
np.linalg.det(X)

6.66133814775094e-16

In [24]:
np.linalg.matrix_rank(X)

2

In [25]:
np.linalg.inv(X)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

No se nos ocurrirá nunca hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior orden (el número de filas / columnas de la misma).

In [27]:
#np.linalg.inv(np.array([[1,2,3],[4,5,6]]))

LinAlgError: Last 2 dimensions of the array must be square